"""add analytics tables: daily_sales, product_views, inventory_alerts

Revision ID: 5bc347048392
Revises: d8f8af77a703
Create Date: 2026-09-27 01:01:26.492450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bc347048392'
down_revision: Union[str, Sequence[str], None] = 'd8f8af77a703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sales_date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_daily_sales_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_sales')),
    sa.UniqueConstraint('sales_date', 'product_id', name='uq_daily_sales_date_product')
    )
    op.create_index(op.f('ix_daily_sales_product_id'), 'daily_sales', ['product_id'], unique=False)
    op.create_index(op.f('ix_daily_sales_sales_date'), 'daily_sales', ['sales_date'], unique=False)
    op.create_table('inventory_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_alerts_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_alerts'))
    )
    op.create_index(op.f('ix_inventory_alerts_product_id'), 'inventory_alerts', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_alerts_resolved_at'), 'inventory_alerts', ['resolved_at'], unique=False)
    op.create_table('product_views',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_views_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_views'))
    )
    op.create_index(op.f('ix_product_views_product_id'), 'product_views', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_views_user_id'), 'product_views', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_views_user_id'), table_name='product_views')
    op.drop_index(op.f('ix_product_views_product_id'), table_name='product_views')
    op.drop_table('product_views')
    op.drop_index(op.f('ix_inventory_alerts_resolved_at'), table_name='inventory_alerts')
    op.drop_index(op.f('ix_inventory_alerts_product_id'), table_name='inventory_alerts')
    op.drop_table('inventory_alerts')
    op.drop_index(op.f('ix_daily_sales_sales_date'), table_name='daily_sales')
    op.drop_index(op.f('ix_daily_sales_product_id'), table_name='daily_sales')
    op.drop_table('daily_sales')
    # ### end Alembic commands ###
