"""add product review workflow + order admin fields

Revision ID: e7d9c697df36
Revises: 5bc347048392
Create Date: 2026-10-03 14:12:22.408293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e7d9c697df36'
down_revision: Union[str, Sequence[str], None] = '5bc347048392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('admin_message', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('reviewed_by', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.alter_column('orders', 'shipping_address',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('orders', 'notes',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_orders_reviewed_by'), 'orders', ['reviewed_by'], unique=False)
    op.drop_constraint(op.f('fk_orders_user_id_users'), 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('fk_orders_reviewed_by_users'), 'orders', 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_orders_user_id_users'), 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('products', sa.Column('review_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='productreviewstatus', native_enum=False, length=20), nullable=False))
    op.add_column('products', sa.Column('reviewed_by', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('review_notes', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('ml_category_slug', sa.String(length=120), nullable=True))
    op.add_column('products', sa.Column('ml_confidence', sa.Numeric(precision=5, scale=4), nullable=True))
    op.create_index(op.f('ix_products_review_status'), 'products', ['review_status'], unique=False)
    op.create_index(op.f('ix_products_reviewed_by'), 'products', ['reviewed_by'], unique=False)
    op.create_foreign_key(op.f('fk_products_reviewed_by_users'), 'products', 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_products_reviewed_by_users'), 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_reviewed_by'), table_name='products')
    op.drop_index(op.f('ix_products_review_status'), table_name='products')
    op.drop_column('products', 'ml_confidence')
    op.drop_column('products', 'ml_category_slug')
    op.drop_column('products', 'review_notes')
    op.drop_column('products', 'reviewed_at')
    op.drop_column('products', 'reviewed_by')
    op.drop_column('products', 'review_status')
    op.drop_constraint(op.f('fk_orders_user_id_users'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('fk_orders_reviewed_by_users'), 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('fk_orders_user_id_users'), 'orders', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_orders_reviewed_by'), table_name='orders')
    op.alter_column('orders', 'notes',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('orders', 'shipping_address',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_column('orders', 'reviewed_at')
    op.drop_column('orders', 'reviewed_by')
    op.drop_column('orders', 'admin_message')
    # ### end Alembic commands ###
